In [1]:
# NumPy

# Theoretical Questions

# 1. Why Use NumPy?
# Imagine trying to process huge amounts of numbers using plain Python lists—it would be slow and inefficient.
# NumPy provides fast arrays, mathematical operations, and powerful tools for scientific computing.
# It's optimized for performance and widely used in data science and machine learning.

# 2. np.mean() vs np.average() - What's the Difference?
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print("Mean (Simple Average):", np.mean(arr))  # Basic mean
print("Weighted Average:", np.average(arr, weights=[1, 1, 1, 2, 2]))  # Uses weights
# Use np.mean() for simple averages, and np.average() when you need weighted calculations.

# 3. How to Reverse an Array?
arr = np.array([1, 2, 3, 4, 5])
print("Reversed Array:", arr[::-1])  # Fastest way

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Flipped Rows:\n", np.flip(arr_2d, axis=0))  # Flip along rows
print("Flipped Columns:\n", np.flip(arr_2d, axis=1))  # Flip along columns

# 4. Checking Data Type
arr = np.array([1, 2, 3])
print("Array Data Type:", arr.dtype)  # Important for memory optimization

# 5. NumPy Arrays vs Python Lists
import time
arr_list = list(range(1000000))
arr_numpy = np.array(arr_list)

start = time.time()
sum(arr_list)
end = time.time()
print("Python List Time Taken:", end - start)

start = time.time()
np.sum(arr_numpy)
end = time.time()
print("NumPy Array Time Taken:", end - start)
# NumPy is way faster because it's built in C, optimized for performance!

# 6. Stacking Arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print("Vertical Stack:\n", np.vstack((a, b)))  # Adds rows
print("Horizontal Stack:\n", np.hstack((a, b.T)))  # Adds columns

# 7. Flip Left-Right vs Up-Down
arr = np.array([[1, 2], [3, 4]])
print("Left-Right Flip:\n", np.fliplr(arr))
print("Up-Down Flip:\n", np.flipud(arr))

# 8. Splitting an Array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("Splitted Arrays:", np.array_split(arr, 3))

# 9. Vectorization & Broadcasting
a = np.array([1, 2, 3])
b = 2
print("Vectorized Multiplication:", a * b)  # NumPy handles it without loops!

# Practical Questions

# 1. Random 3x3 Array & Transpose
arr = np.random.randint(1, 100, (3, 3))
print("Original 3x3 Matrix:\n", arr)
print("Transposed Matrix:\n", arr.T)

# 2. Reshaping a 1D Array
arr = np.arange(10)
print("2x5 Shape:\n", arr.reshape(2, 5))
print("5x2 Shape:\n", arr.reshape(5, 2))

# 3. 4x4 Random Array with a Zero Border
arr = np.random.rand(4, 4)
arr_with_border = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("With Zero Border:\n", arr_with_border)

# 4. Generate a Stepwise Array
arr = np.arange(10, 65, 5)
print("Stepwise Array:", arr)

# 5. String Transformations
arr = np.array(['python', 'numpy', 'pandas'])
print("Uppercase:", np.char.upper(arr))
print("Lowercase:", np.char.lower(arr))
print("Title Case:", np.char.title(arr))

# 6. Insert Space Between Letters
arr = np.array(['hello', 'world'])
print("Spaced Out Words:", np.char.join(' ', arr))

# 7. Operations on 2D Arrays
a = np.random.randint(1, 10, (2, 2))
b = np.random.randint(1, 10, (2, 2))
print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)

# 8. Identity Matrix & Diagonal Extraction
arr = np.eye(5)
print("Diagonal Elements:", np.diag(arr))

# 9. Find Prime Numbers in a Random Array
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

arr = np.random.randint(0, 1000, 100)
primes = arr[np.vectorize(is_prime)(arr)]
print("Prime Numbers Found:", primes)

# 10. Weekly Temperature Averages
temps = np.random.randint(15, 40, 30)
weekly_avg = temps.reshape(5, 6).mean(axis=1)
print("Weekly Temperature Averages:", weekly_avg)


Mean (Simple Average): 3.0
Weighted Average: 3.4285714285714284
Reversed Array: [5 4 3 2 1]
Flipped Rows:
 [[7 8 9]
 [4 5 6]
 [1 2 3]]
Flipped Columns:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]
Array Data Type: int64
Python List Time Taken: 0.012625455856323242
NumPy Array Time Taken: 0.005173921585083008
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]]
Horizontal Stack:
 [[1 2 5]
 [3 4 6]]
Left-Right Flip:
 [[2 1]
 [4 3]]
Up-Down Flip:
 [[3 4]
 [1 2]]
Splitted Arrays: [array([1, 2, 3]), array([4, 5]), array([6, 7])]
Vectorized Multiplication: [2 4 6]
Original 3x3 Matrix:
 [[55  1 58]
 [95 40 54]
 [88 90 59]]
Transposed Matrix:
 [[55 95 88]
 [ 1 40 90]
 [58 54 59]]
2x5 Shape:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Shape:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
With Zero Border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.73262407 0.51411993 0.2454105  0.23168491 0.        ]
 [0.         0.59534129 0.40824058 0.4438815  0.24744072 0.        ]
 [0.         0.38819078 0.20086262 0